version: '3.8'

services:
  db:
    image: mongo:5.0.0
    container_name: healthify
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db
    restart: always
